name: Rust Workflow
run-name: Rust Lint + Build + Tests
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  fmt:
    runs-on: ubuntu-latest
    container:
      image: rust:1.90.0-alpine3.22
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Format
        run: cargo fmt -- --check

  lint:
    runs-on: ubuntu-latest
    container:
      image: rust:1.90.0-alpine3.22
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup rust build cache
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-rustlint-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-rustlint-
      - name: Clippy
        run: cargo clippy --tests -- -Dwarnings

  build-and-test-sbf:
    runs-on: ubuntu-latest
    container:
      image: solanafoundation/solana-verifiable-build:2.2.20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup rust build cache
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-sbf-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-sbf-
      - name: Build
        run: cargo-build-sbf
      - name: Test
        run: cargo-test-sbf
