[package]
name = "inf1-pp-flatfee-std"
version = "0.2.0"
edition.workspace = true
license-file.workspace = true

[dependencies]
inf1-pp-core = { workspace = true }
inf1-pp-flatfee-core = { workspace = true }
inf1-pp-std = { workspace = true }
