[package]
name = "inf1-pp-flatslab-core"
edition.workspace = true
license-file.workspace = true
version.workspace = true

[dependencies]
generic-array-struct = { workspace = true }
inf1-pp-core = { workspace = true } 

[dev-dependencies]
proptest = { workspace = true, features = ["std"] }
