[package]
name = "inf1-pp-flatslab-core"
edition.workspace = true
license-file.workspace = true
version.workspace = true

[dependencies]

[dev-dependencies]
proptest = { workspace = true, features = ["std"] }
