[package]
name = "inf1-pp-std"
edition.workspace = true
license-file.workspace = true
version.workspace = true

[dependencies]
inf1-pp-core = { workspace = true }
inf1-update-traits = { workspace = true }
