[package]
name = "inf1-pp-flatslab-std"
edition.workspace = true
license-file.workspace = true
version.workspace = true

[dependencies]
inf1-pp-flatslab-core = { workspace = true }
inf1-pp-std = { workspace = true }
