[package]
name = "inf1-svc-lido-std"
edition.workspace = true
license-file.workspace = true
version.workspace = true

[dependencies]
inf1-svc-lido-core = { workspace = true }
inf1-svc-std = { workspace = true }
