# Required input env vars
# - RUSTVERS

name: "Restore wasm Package Cache"
description: "Restores wasm npm package output from cache"
inputs:
  fail-on-cache-miss:
    description: "fwd to actions/cache/restore"
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: wasm Package Cache Restore
      uses: actions/cache/restore@v4
      with:
        fail-on-cache-miss: ${{ inputs.fail-on-cache-miss }}
        # Make sure vars match those in save-cache-wasm-pkg/action.yaml
        path: |
          ts/sdk/pkg
        key: ${{ runner.os }}-wasmpkg-${{ env.RUSTVERS }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-wasmpkg-
